/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ApiApplicationsRouteImport } from './routes/api/applications'
import { Route as ApiAuditRouteImport } from './routes/api/audit'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApplicationIndexRouteImport } from './routes/application.index'
import { Route as ApplicationIdRouteImport } from './routes/application.$id'
import { Route as FounderIdRouteImport } from './routes/founder.$id'
import { Route as ApiApplicationsIdRouteImport } from './routes/api/applications.$id'
import { Route as ApiDecisionsQueueRouteImport } from './routes/api/decisions.queue'
import { Route as ApiFoundersIdRouteImport } from './routes/api/founders.$id'
import { Route as ApiApplicationsIdAdversaryRouteImport } from './routes/api/applications.$id.adversary'
import { Route as ApiDecisionsIdDecideRouteImport } from './routes/api/decisions.$id.decide'
import { Route as ApiFoundersIdActivateRouteImport } from './routes/api/founders.$id.activate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsRoute = ApiApplicationsRouteImport.update({
  id: '/api/applications',
  path: '/api/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditRoute = ApiAuditRouteImport.update({
  id: '/api/audit',
  path: '/api/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationIndexRoute = ApplicationIndexRouteImport.update({
  id: '/application/',
  path: '/application/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationIdRoute = ApplicationIdRouteImport.update({
  id: '/application/$id',
  path: '/application/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderIdRoute = FounderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FounderRoute,
} as any)
const ApiApplicationsIdRoute = ApiApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiApplicationsRoute,
} as any)
const ApiDecisionsQueueRoute = ApiDecisionsQueueRouteImport.update({
  id: '/api/decisions/queue',
  path: '/api/decisions/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoundersIdRoute = ApiFoundersIdRouteImport.update({
  id: '/api/founders/$id',
  path: '/api/founders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsIdAdversaryRoute =
  ApiApplicationsIdAdversaryRouteImport.update({
    id: '/adversary',
    path: '/adversary',
    getParentRoute: () => ApiApplicationsIdRoute,
  } as any)
const ApiDecisionsIdDecideRoute = ApiDecisionsIdDecideRouteImport.update({
  id: '/api/decisions/$id/decide',
  path: '/api/decisions/$id/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoundersIdActivateRoute = ApiFoundersIdActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => ApiFoundersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/founder': typeof FounderRouteWithChildren
  '/queue': typeof QueueRoute
  '/api/applications': typeof ApiApplicationsRouteWithChildren
  '/api/audit': typeof ApiAuditRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/query': typeof ApiQueryRoute
  '/application/$id': typeof ApplicationIdRoute
  '/founder/$id': typeof FounderIdRoute
  '/application/': typeof ApplicationIndexRoute
  '/api/applications/$id': typeof ApiApplicationsIdRouteWithChildren
  '/api/decisions/queue': typeof ApiDecisionsQueueRoute
  '/api/founders/$id': typeof ApiFoundersIdRouteWithChildren
  '/api/applications/$id/adversary': typeof ApiApplicationsIdAdversaryRoute
  '/api/decisions/$id/decide': typeof ApiDecisionsIdDecideRoute
  '/api/founders/$id/activate': typeof ApiFoundersIdActivateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/founder': typeof FounderRouteWithChildren
  '/queue': typeof QueueRoute
  '/api/applications': typeof ApiApplicationsRouteWithChildren
  '/api/audit': typeof ApiAuditRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/query': typeof ApiQueryRoute
  '/application/$id': typeof ApplicationIdRoute
  '/founder/$id': typeof FounderIdRoute
  '/application': typeof ApplicationIndexRoute
  '/api/applications/$id': typeof ApiApplicationsIdRouteWithChildren
  '/api/decisions/queue': typeof ApiDecisionsQueueRoute
  '/api/founders/$id': typeof ApiFoundersIdRouteWithChildren
  '/api/applications/$id/adversary': typeof ApiApplicationsIdAdversaryRoute
  '/api/decisions/$id/decide': typeof ApiDecisionsIdDecideRoute
  '/api/founders/$id/activate': typeof ApiFoundersIdActivateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/founder': typeof FounderRouteWithChildren
  '/queue': typeof QueueRoute
  '/api/applications': typeof ApiApplicationsRouteWithChildren
  '/api/audit': typeof ApiAuditRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/query': typeof ApiQueryRoute
  '/application/$id': typeof ApplicationIdRoute
  '/founder/$id': typeof FounderIdRoute
  '/application/': typeof ApplicationIndexRoute
  '/api/applications/$id': typeof ApiApplicationsIdRouteWithChildren
  '/api/decisions/queue': typeof ApiDecisionsQueueRoute
  '/api/founders/$id': typeof ApiFoundersIdRouteWithChildren
  '/api/applications/$id/adversary': typeof ApiApplicationsIdAdversaryRoute
  '/api/decisions/$id/decide': typeof ApiDecisionsIdDecideRoute
  '/api/founders/$id/activate': typeof ApiFoundersIdActivateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/founder'
    | '/queue'
    | '/api/applications'
    | '/api/audit'
    | '/api/dashboard'
    | '/api/metrics'
    | '/api/query'
    | '/application/$id'
    | '/founder/$id'
    | '/application/'
    | '/api/applications/$id'
    | '/api/decisions/queue'
    | '/api/founders/$id'
    | '/api/applications/$id/adversary'
    | '/api/decisions/$id/decide'
    | '/api/founders/$id/activate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/founder'
    | '/queue'
    | '/api/applications'
    | '/api/audit'
    | '/api/dashboard'
    | '/api/metrics'
    | '/api/query'
    | '/application/$id'
    | '/founder/$id'
    | '/application'
    | '/api/applications/$id'
    | '/api/decisions/queue'
    | '/api/founders/$id'
    | '/api/applications/$id/adversary'
    | '/api/decisions/$id/decide'
    | '/api/founders/$id/activate'
  id:
    | '__root__'
    | '/'
    | '/founder'
    | '/queue'
    | '/api/applications'
    | '/api/audit'
    | '/api/dashboard'
    | '/api/metrics'
    | '/api/query'
    | '/application/$id'
    | '/founder/$id'
    | '/application/'
    | '/api/applications/$id'
    | '/api/decisions/queue'
    | '/api/founders/$id'
    | '/api/applications/$id/adversary'
    | '/api/decisions/$id/decide'
    | '/api/founders/$id/activate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FounderRoute: typeof FounderRouteWithChildren
  QueueRoute: typeof QueueRoute
  ApiApplicationsRoute: typeof ApiApplicationsRouteWithChildren
  ApiAuditRoute: typeof ApiAuditRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApplicationIdRoute: typeof ApplicationIdRoute
  ApplicationIndexRoute: typeof ApplicationIndexRoute
  ApiDecisionsQueueRoute: typeof ApiDecisionsQueueRoute
  ApiFoundersIdRoute: typeof ApiFoundersIdRouteWithChildren
  ApiDecisionsIdDecideRoute: typeof ApiDecisionsIdDecideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications': {
      id: '/api/applications'
      path: '/api/applications'
      fullPath: '/api/applications'
      preLoaderRoute: typeof ApiApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit': {
      id: '/api/audit'
      path: '/api/audit'
      fullPath: '/api/audit'
      preLoaderRoute: typeof ApiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application/': {
      id: '/application/'
      path: '/application'
      fullPath: '/application/'
      preLoaderRoute: typeof ApplicationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application/$id': {
      id: '/application/$id'
      path: '/application/$id'
      fullPath: '/application/$id'
      preLoaderRoute: typeof ApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/$id': {
      id: '/founder/$id'
      path: '/$id'
      fullPath: '/founder/$id'
      preLoaderRoute: typeof FounderIdRouteImport
      parentRoute: typeof FounderRoute
    }
    '/api/applications/$id': {
      id: '/api/applications/$id'
      path: '/$id'
      fullPath: '/api/applications/$id'
      preLoaderRoute: typeof ApiApplicationsIdRouteImport
      parentRoute: typeof ApiApplicationsRoute
    }
    '/api/decisions/queue': {
      id: '/api/decisions/queue'
      path: '/api/decisions/queue'
      fullPath: '/api/decisions/queue'
      preLoaderRoute: typeof ApiDecisionsQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/founders/$id': {
      id: '/api/founders/$id'
      path: '/api/founders/$id'
      fullPath: '/api/founders/$id'
      preLoaderRoute: typeof ApiFoundersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications/$id/adversary': {
      id: '/api/applications/$id/adversary'
      path: '/adversary'
      fullPath: '/api/applications/$id/adversary'
      preLoaderRoute: typeof ApiApplicationsIdAdversaryRouteImport
      parentRoute: typeof ApiApplicationsIdRoute
    }
    '/api/decisions/$id/decide': {
      id: '/api/decisions/$id/decide'
      path: '/api/decisions/$id/decide'
      fullPath: '/api/decisions/$id/decide'
      preLoaderRoute: typeof ApiDecisionsIdDecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/founders/$id/activate': {
      id: '/api/founders/$id/activate'
      path: '/activate'
      fullPath: '/api/founders/$id/activate'
      preLoaderRoute: typeof ApiFoundersIdActivateRouteImport
      parentRoute: typeof ApiFoundersIdRoute
    }
  }
}

interface FounderRouteChildren {
  FounderIdRoute: typeof FounderIdRoute
}

const FounderRouteChildren: FounderRouteChildren = {
  FounderIdRoute: FounderIdRoute,
}

const FounderRouteWithChildren =
  FounderRoute._addFileChildren(FounderRouteChildren)

interface ApiApplicationsIdRouteChildren {
  ApiApplicationsIdAdversaryRoute: typeof ApiApplicationsIdAdversaryRoute
}

const ApiApplicationsIdRouteChildren: ApiApplicationsIdRouteChildren = {
  ApiApplicationsIdAdversaryRoute: ApiApplicationsIdAdversaryRoute,
}

const ApiApplicationsIdRouteWithChildren =
  ApiApplicationsIdRoute._addFileChildren(ApiApplicationsIdRouteChildren)

interface ApiApplicationsRouteChildren {
  ApiApplicationsIdRoute: typeof ApiApplicationsIdRouteWithChildren
}

const ApiApplicationsRouteChildren: ApiApplicationsRouteChildren = {
  ApiApplicationsIdRoute: ApiApplicationsIdRouteWithChildren,
}

const ApiApplicationsRouteWithChildren = ApiApplicationsRoute._addFileChildren(
  ApiApplicationsRouteChildren,
)

interface ApiFoundersIdRouteChildren {
  ApiFoundersIdActivateRoute: typeof ApiFoundersIdActivateRoute
}

const ApiFoundersIdRouteChildren: ApiFoundersIdRouteChildren = {
  ApiFoundersIdActivateRoute: ApiFoundersIdActivateRoute,
}

const ApiFoundersIdRouteWithChildren = ApiFoundersIdRoute._addFileChildren(
  ApiFoundersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FounderRoute: FounderRouteWithChildren,
  QueueRoute: QueueRoute,
  ApiApplicationsRoute: ApiApplicationsRouteWithChildren,
  ApiAuditRoute: ApiAuditRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApplicationIdRoute: ApplicationIdRoute,
  ApplicationIndexRoute: ApplicationIndexRoute,
  ApiDecisionsQueueRoute: ApiDecisionsQueueRoute,
  ApiFoundersIdRoute: ApiFoundersIdRouteWithChildren,
  ApiDecisionsIdDecideRoute: ApiDecisionsIdDecideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
